# Generated by Django 4.0.1 on 2022-06-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(default='https://picsum.photos/600', max_length=1024),
        ),
    ]
